### ISSUE TITLE
Node version 11.0.0 not working

### ISSUE THREAD

**Issue by slonka** [lev-kazakov/node-cmake-generator#1]
Hi,

I have a problem setting it up, newer versions of node fail with:

```
CMake Error at CMakeLists.txt:2566 (add_library):
  No SOURCES given to target: v8_external_snapshot
```

And older (8.9.0) with:

```
WARNING: warnings were emitted in the configure phase
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

Traceback (most recent call last):
  File "./node/configure", line 1491, in <module>
    run_gyp(gyp_args)
  File "./node/tools/gyp_node.py", line 53, in run_gyp
    rc = gyp.main(args)
  File "./node/tools/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "./node/tools/gyp/pylib/gyp/__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "./node/tools/gyp/pylib/gyp/generator/make.py", line 2179, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File "./node/tools/gyp/pylib/gyp/generator/make.py", line 800, in Write
    self.Pchify))
  File "./node/tools/gyp/pylib/gyp/generator/make.py", line 1195, in WriteSources
    cflags = self.xcode_settings.GetCflags(configname)
  File "./node/tools/gyp/pylib/gyp/xcode_emulation.py", line 628, in GetCflags
    archs = self.GetActiveArchs(self.configname)
  File "./node/tools/gyp/pylib/gyp/xcode_emulation.py", line 486, in GetActiveArchs
    xcode_archs_default = GetXcodeArchsDefault()
  File "./node/tools/gyp/pylib/gyp/xcode_emulation.py", line 118, in GetXcodeArchsDefault
    xcode_version, _ = XcodeVersion()
  File "./node/tools/gyp/pylib/gyp/xcode_emulation.py", line 1406, in XcodeVersion
    version = re.match(r'(\d\.\d\.?\d*)', version).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
(node:1747) UnhandledPromiseRejectionWarning: configure exited with code 1
(node:1747) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1747) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Would really appreciate helping setting it up. Do I need to install xcode?

**Comment by lev-kazakov** [comment]
hi, yes, Xcode needs to be installed. 
i've updated the readme, thx.
tested with latest node master (12.0.0-pre), all good.

**Comment by gengjiawen** [comment]
@lev-kazakov Still the same issue
```
-- Configuring done
CMake Error at CMakeLists.txt:2566 (add_library):
  No SOURCES given to target: v8_external_snapshot
```
env
```
cmake version: 3.12.4
macOS: 10.14
```

**Comment by gengjiawen** [comment]
Downgrade cmake fix my issue
```bash
brew unlink cmake
brew install https://github.com/Homebrew/homebrew-core/raw/db6f7662e568a4172d852799bf617fd41f98fc75/Formula/cmake.rb
```

**Comment by lev-kazakov** [comment]
@gengjiawen thx. which `cmake` version were you using?

**Comment by lev-kazakov** [comment]
@gengjiawen sorry i intended to delete my own comment :)
@gengjiawen's issue was solved by downgrading `cmake`.
